name: Build unsigned debug application package kit

on:
  workflow_dispatch

jobs:
  pre_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit_tests:
    needs: [ pre_build ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: ./gradlew test

  android_tests:
    needs: [ pre_build ]
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedAndroidTest

  build_apk:
    needs: [ unit_tests, android_tests, pre_build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build unsigned debug apk
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
